- nodeset:
    name: shared
    nodes:
      - name: shared
        label: centos76
        
- nodeset:
    name: emea
    nodes:
      - name: emea
        label: ubuntu-bionic
        
- nodeset:
    name: nafta
    nodes:
      - name: nafta
        label: centos76

- job:
    name: sparkbuild
    run: playbooks/sparkbuild.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
      
- job:
    name: builddsparkdocker
    run: playbooks/builddsparkdocker.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
 
- job:
    name: sparksubmit
    run: playbooks/sparksubmit.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
      
- job:
    name: checkdatalocation_both
    run: playbooks/checkdatalocation_both.yaml
    parent: base 

- job:
    name: checkdatalocation_emea
    run: playbooks/checkdatalocation_emea.yaml
    parent: base 
 
- job:
    name: checkbuildlocation_nafta
    run: playbooks/checkdatalocation_nafta.yaml
    parent: base    
      
- project:
    check_emea:
      jobs:
        - sparkbuild:
            host-vars:
              emea:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog_shared: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: emea    
        - builddsparkdocker:
            dependencies:
              - sparkbuild
            host-vars:
              emea:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog_shared: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: emea   
        - sparksubmit:
            dependencies:
              - sparkbuild
              - builddsparkdocker
            host-vars:
              emea:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog_shared: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: emea
            
    check_nafta:
      jobs:
        - sparkbuild:
            host-vars:
              nafta:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog_shared: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta    
        - builddsparkdocker:
            dependencies:
              - sparkbuild
            host-vars:
              nafta:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog_shared: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta   
        - sparksubmit:
            dependencies:
              - sparkbuild
              - builddsparkdocker
            host-vars:
              nafta:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog_shared: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta              
    sparkbuildjob_shared:
      jobs: 
        - sparkbuild:
            host-vars:
              shared:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: shared
        - checkdatalocation_emea:
            dependencies:
              - sparkbuild
        - builddsparkdocker:
            dependencies:
              - sparkbuild
              - checkdatalocation_emea
            host-vars:
              emea:
                jfrog_shared: "http://13.234.232.162:9083"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea
        - sparksubmit:
            dependencies:
              - sparkbuild
              - checkdatalocation_emea
              - builddsparkdocker
            host-vars:
              emea:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea       
