- nodeset:
    name: both_region
    nodes:
      - name: node1
        label: ubuntu-bionic
      - name: node2
        label: centos76
        
- nodeset:
    name: emea
    nodes:
      - name: emea
        label: ubuntu-bionic
        
- nodeset:
    name: nafta
    nodes:
      - name: nafta
        label: centos76

- job:
    name: runsparkjob
    run: playbooks/runsparkjob.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
      
- job:
    name: checkbuildlocation_both
    run: playbooks/checkbuildlocation_both.yaml
    parent: base 

- job:
    name: checkbuildlocation_emea
    run: playbooks/checkbuildlocation_emea.yaml
    parent: base 
 
- job:
    name: checkbuildlocation_nafta
    run: playbooks/checkbuildlocation_nafta.yaml
    parent: base  
    
      
- project:
    checklabel_both:
      jobs:
        - checkbuildlocation_both:
            nodeset: emea
    checklabel_emea:
      jobs:
       - checkbuildlocation_emea:
           nodeset: emea
    checklabel_nafta:
      jobs:
       - checkbuildlocation_nafta:
           nodeset: nafta
           
    check_emea:
      jobs:
        - runsparkjob:
            host-vars:
              emea:
                jfrog: "http://172.31.27.120:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
            nodeset: emea
    check_nafta:
      jobs:
        - runsparkjob:
            host-vars: 
              nafta:
                jfrog: "http://172.31.20.175:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta 
