
- nodeset:
    name: emea
    nodes:
      - name: node1
        label: ubuntu-bionic
  host-vars:
     jfrog: "http://172.31.27.120:9083"
     jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
        
- nodeset:
    name: nafta
    nodes:
      - name: node2
        label: centos76
  host-vars:
    jfrog: "http://172.31.20.175:9083"
    jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"

- job:
    name: runsparkjob
    run: playbooks/runsparkjob.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
      
- job:
    name: buildlocation
    run: playbooks/build_location.yaml
    parent: base 
    
      
- project:
    checklabel_both:
      jobs:
        - buildlocation:
            nodeset: emea-node 
    check_emea:
      jobs:
        - runsparkjob:
#            host-vars:
#              node1:
#                jfrog: "http://172.31.27.120:9083"
#                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
            nodeset: emea
