- nodeset:
    name: shared
    nodes:
      - name: shared
        label: centos76
        
- nodeset:
    name: emea
    nodes:
      - name: emea
        label: ubuntu-bionic
        
- nodeset:
    name: nafta
    nodes:
      - name: nafta
        label: centos76

- job:
    name: sparkbuild
    run: playbooks/sparkbuild.yaml
    parent: base
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
      
- job:
    name: builddsparkdocker
    run: playbooks/buildsparkdocker.yaml
    parent: sparkbuild
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$

- job:
    name: builddsparkdocker_shared
    run: playbooks/buildsparkdocker_shared.yaml
    parent: sparkbuild
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
 
- job:
    name: sparksubmit
    run: playbooks/sparksubmit.yaml
    parent: builddsparkdocker
    irrelevant-files:
      - ^playbooks/.*$
      - ^.zuul.yaml$
      
- job:
    name: checkdatalocation_both
    run: playbooks/checkdatalocation_both.yaml
    parent: base 

- job:
    name: checkdatalocation_emea
    run: playbooks/checkdatalocation_emea.yaml
    parent: base 
 
- job:
    name: checkbuildlocation_nafta
    run: playbooks/checkdatalocation_nafta.yaml
    parent: base    
      
- project:
    checklabel_both:
      jobs:
       - checkdatalocation_both:
           nodeset: emea
    checklabel_nafta_datalocation:
      jobs:
       - checkbuildlocation_nafta:
           nodeset: nafta      
    checklabel_emea_datalocation:
      jobs:
       - checkdatalocation_emea:
           nodeset: nafta  
    check_emea:
      jobs:
        - sparkbuild:
            host-vars:
              emea:
#                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
            nodeset: emea    
        - builddsparkdocker:
            dependencies:
              - sparkbuild
            host-vars:
              emea:
#                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
            nodeset: emea   
        - sparksubmit:
            dependencies:
              - sparkbuild
              - builddsparkdocker
            host-vars:
              emea:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083" 
                jfrog: "http://ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
                jfrog_api_token: "AKCp5dKPSCchSnYWq9RDxLwpTrEcMJpJR2ikAXMAr8CnHdaHMC9Jdykio1xWqRe68pga4NEpJ"
            nodeset: emea
            
    check_nafta:
      jobs:
        - sparkbuild:
            host-vars:
              nafta:
#                jfrog_docker: "13.235.19.10:9083" 
                jfrog: "http://13.233.110.128:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta    
        - builddsparkdocker:
            dependencies:
              - sparkbuild
            host-vars:
              nafta:
 #               jfrog_docker: "13.235.19.10:9083" 
                jfrog: "http://13.233.110.128:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta   
        - sparksubmit:
            dependencies:
              - sparkbuild
              - builddsparkdocker
            host-vars:
              nafta:
                jfrog_docker: "13.233.110.128:9083" 
                jfrog: "http://13.233.110.128:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: nafta              
    sparkbuildjob_shared:
      jobs: 
        - sparkbuild:
            host-vars:
              shared:
                jfrog: "http://13.233.110.128:9083"
                jfrog_api_token: "AKCp5dKPSD6DjaJRUb6xeXtxLhWUdgnQ5gUDCp9XgFU3ag6wDutAmgD4cMNts9bjmbdWwejoC"
            nodeset: shared
        - checkdatalocation_emea:
            dependencies:
              - sparkbuild
        - builddsparkdocker_shared:
            dependencies:
              - sparkbuild
              - checkdatalocation_emea          
            host-vars:
              emea:
                jfrog: "http://13.233.110.128:9083"
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com:9083"
            nodeset: emea
        - sparksubmit:
            dependencies:
              - sparkbuild
              - builddsparkdocker_shared
            host-vars:
              emea:
                jfrog_docker: "ec2-13-126-181-144.ap-south-1.compute.amazonaws.com"
            nodeset: emea       
