- hosts: all
  tasks:
   - name: Pull the jar file
     get_url:
        url: "{{ jfrog_shared }}/artifactory/generic-local/writeRead-assembly-{{ pullid.stdout }}.jar"
        dest: /home/ec2-user/work/
     when: build_status is succeeded

   - name: build the docker file
     shell: |
            echo "FROM {{ jfrog_shared }}/docker-local/spark:v2.4.3" > /home/ec2-user/work/Dockerfile
            echo "COPY writeRead-assembly-0.1.jar   //opt/spark/writeRead-assembly-0.1.jar" >> /home/ec2-user/work/Dockerfile
     when: build_status is succeeded
     
  - name : build the docker image 
    shell: |
          cd /home/ec2-user/work/
          docker build -t {{ jfrog }}/docker-local/cassandra_example:latest .	

  - name : push the docker images 
    shell: |
          docker push {{ jfrog }}/docker-local/cassandra_example:latest 
