- hosts: all
  tasks:
    - debug:
        msg: "{{ inventory_hostname }}"
    - set_fact:
         hostname: "{{ inventory_hostname }}"
    - shell: |
            echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid
    - name: getting the project name of pull request
      debug:
        msg: "{{ zuul.project.name }}"
    - name: display pull id
      debug:
        msg: "{{ pullid }}"
    - set_fact:
        pull_id: "{{ pullid.stdout }}"
    - shell: |
            curl -s https://api.github.com/repos/{{ zuul.project.name }}/pulls/{{ pull_id }}| jq .head.ref
      register: branch
      args:
        warn: false
    - set_fact:
        branch_name: "{{ branch.stdout }}"
    - debug:
        msg: "{{ branch_name }}" 
        
    - name: "Include emea"
      include: emea_build.yaml
      when: "'emea' in hostname "
    
    - name: "Inlcude nafta"
      include: nafta_build.yaml
      when: "'nafta' in hostname "
      
