- hosts: all
  gather_facts: false
  tasks:
    - shell: |
            echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid
    - debug:
        msg: "running spark cassandra demo"

    - name: "Deleted the workspace dir before build"
      shell: |
            rm -rf ~/spark_work
      register: spark_output

    - name: Clone git repo
      git:
        repo: https://github.com/zuul-hcl-org/spark-cassandra.git
        dest: ~/spark_work/
      when: spark_output is succeeded

    - name: Build sample project and junit reports
      shell: |
            cd ~/spark_work/java/sbt/oss
            sbt clean assembly

      register: build_status

    - name: Push artifacts to jfrog repository
      uri:
        url: "{{ jfrog }}/artifactory/generic-local/writeRead-assembly-{{ pullid.stdout }}.jar"
        #when: zuul_location in emea
        validate_certs: no
        method: PUT
        headers:
          X-JFrog-Art-Api: "{{ jfrog_api_token }}"
        src: ~/spark_work/java/sbt/oss/target/writeRead-assembly-0.1.jar
        status_code: 201
        remote_src: yes
      when: build_status is succeeded
