- hosts: all
  tasks:
    - shell: |
            echo {{ zuul.change_url }} | cut -d '/' -f 7
      register: pullid 
        
    - name: " run the spark submit"
      shell: |
             /home/ec2-user/spark-2.4.3-bin-hadoop2.7/bin//spark-submit \
             --master k8s://https://54.71.211.15:9443/k8s/clusters/c-7npzk \
             --deploy-mode cluster \
             --name spark-readwirte-example \
             --class com.datastax.spark.example.WriteRead \
             --conf spark.executor.instances=3 \
             --conf spark.kubernetes.container.image.pullSecrets=dockersecret \
             --conf spark.executor.memory=500m \
             --conf spark.driver.memory=500m  \
             --conf spark.kubernetes.executor.request.cores=0.5 \
             --conf spark.kubernetes.driver.request.cores=0.5 \
             --conf spark.kubernetes.container.image={{ jfrog_docker }}/docker-local/cassandra_example:v{{ pullid.stdout }} \
             --conf spark.kubernetes.namespace=spark \
             --conf spark.driver.host=local[1] \
             --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
             --conf spark.jars.packages=datastax:spark-cassandra-connector:2.4.0-s_2.11 \
             --conf spark.cassandra.connection.host=172.31.20.175 \
             local:///opt/spark/writeRead-assembly-0.1.jar
      register: spark_submit_output
